---
   - name: Add-domain-name
     lineinfile:
        path: /etc/hosts
        state: present
        regexp: '^#?127.0.1.1 localhost;'
        line: '127.0.1.1 localhost "{{ domain_name }}";'

   - name: Add-domain-name-ip6
     lineinfile:
        path: /etc/hosts
        state: present
        regexp: '^#?::1 ip6-localhost ip6-loopback'
        line: '::1 ip6-localhost ip6-loopback ip6-"{{domain_name}}"'


